<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>aiguibin-database-excel</artifactId>
        <groupId>com.aiguibin</groupId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.aiguibin</groupId>
    <artifactId>database-excel-cli</artifactId>

    <build>
        <plugins>
            <!-- 显式覆盖父工程的 spring-boot-maven-plugin 配置 -->
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <skip>true</skip> <!-- 跳过 repackage -->
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>