server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/aiguibin_online_tables?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
    username: root
    password: P@ssW0rd
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
  sql:
    init:
      mode: never


mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      logic-delete-field: isDeleted
      logic-delete-value: 1
      logic-not-delete-value: 0
    banner: false

logging:
  level:
    root: INFO
    com.aiguibin.online.table: INFO
    com.aiguibin.online.table.mapper: DEBUG
