-- 创建字典类型变更主表
CREATE TABLE `biz_ddct_type_change` (
  `id` varchar(32) NOT NULL COMMENT '主键ID',
  `change_no` varchar(50) NOT NULL COMMENT '变更单号',
  `dct_tp_id` varchar(32) DEFAULT NULL COMMENT '关联字典类型ID',
  `change_type` varchar(10) NOT NULL COMMENT '变更类型：ADD-新增，MOD-修改，DEL-删除',
  `old_dct_tp` varchar(50) DEFAULT NULL COMMENT '原始字典类型编码',
  `new_dct_tp` varchar(50) DEFAULT NULL COMMENT '新字典类型编码',
  `old_dct_tp_nm` varchar(100) DEFAULT NULL COMMENT '原始字典类型名称',
  `new_dct_tp_nm` varchar(100) DEFAULT NULL COMMENT '新字典类型名称',
  `change_reason` varchar(500) NOT NULL COMMENT '变更原因',
  `change_impact` varchar(1000) DEFAULT NULL COMMENT '变更影响',
  `apply_user` varchar(32) NOT NULL COMMENT '申请人',
  `apply_time` datetime NOT NULL COMMENT '申请时间',
  `approve_status` varchar(20) NOT NULL DEFAULT 'PENDING' COMMENT '审批状态：DRAFT-草稿，PENDING-待审批，APPROVED-已通过，REJECTED-已拒绝，CANCELED-已取消',
  `execute_status` varchar(20) NOT NULL DEFAULT 'PENDING' COMMENT '执行状态：PENDING-待执行，EXECUTING-执行中，SUCCESS-成功，FAILED-失败',
  `approve_user` varchar(32) DEFAULT NULL COMMENT '审批人',
  `approve_time` datetime DEFAULT NULL COMMENT '审批时间',
  `approve_remark` varchar(500) DEFAULT NULL COMMENT '审批意见',
  `execute_user` varchar(32) DEFAULT NULL COMMENT '执行人',
  `execute_time` datetime DEFAULT NULL COMMENT '执行时间',
  `execute_result` varchar(1000) DEFAULT NULL COMMENT '执行结果',
  `item_add_count` int DEFAULT '0' COMMENT '新增字典项数量',
  `item_mod_count` int DEFAULT '0' COMMENT '修改字典项数量',
  `item_del_count` int DEFAULT '0' COMMENT '删除字典项数量',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `is_deleted` tinyint NOT NULL DEFAULT '0' COMMENT '是否删除：0-否，1-是',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_change_no` (`change_no`),
  KEY `idx_approve_status` (`approve_status`),
  KEY `idx_execute_status` (`execute_status`),
  KEY `idx_apply_time` (`apply_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='字典类型变更主表';

-- 创建字典项变更明细表
CREATE TABLE `biz_ddct_item_change` (
  `id` varchar(32) NOT NULL COMMENT '主键ID',
  `change_id` varchar(32) NOT NULL COMMENT '关联变更主表ID',
  `change_operation` varchar(10) NOT NULL COMMENT '操作类型：ADD-新增，MOD-修改，DEL-删除',
  `old_dct_seq` int DEFAULT NULL COMMENT '原始排序号',
  `new_dct_seq` int DEFAULT NULL COMMENT '新排序号',
  `old_dct_grp` varchar(50) DEFAULT NULL COMMENT '原始分组',
  `new_dct_grp` varchar(50) DEFAULT NULL COMMENT '新分组',
  `old_dct_key` varchar(50) DEFAULT NULL COMMENT '原始字典键',
  `new_dct_key` varchar(50) DEFAULT NULL COMMENT '新字典键',
  `old_dct_val_nm` varchar(100) DEFAULT NULL COMMENT '原始字典值名称',
  `new_dct_val_nm` varchar(100) DEFAULT NULL COMMENT '新字典值名称',
  `old_dct_val` varchar(255) DEFAULT NULL COMMENT '原始字典值',
  `new_dct_val` varchar(255) DEFAULT NULL COMMENT '新字典值',
  `old_dct_dsc` varchar(500) DEFAULT NULL COMMENT '原始字典描述',
  `new_dct_dsc` varchar(500) DEFAULT NULL COMMENT '新字典描述',
  `old_stcd` varchar(10) DEFAULT NULL COMMENT '原始状态',
  `new_stcd` varchar(10) DEFAULT NULL COMMENT '新状态',
  `execute_status` varchar(20) NOT NULL DEFAULT 'PENDING' COMMENT '执行状态：PENDING-待执行，SUCCESS-成功，FAILED-失败',
  `execute_result` varchar(500) DEFAULT NULL COMMENT '执行结果',
  `item_order` int NOT NULL DEFAULT '0' COMMENT '字典项顺序',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `is_deleted` tinyint NOT NULL DEFAULT '0' COMMENT '是否删除：0-否，1-是',
  PRIMARY KEY (`id`),
  KEY `idx_change_id` (`change_id`),
  KEY `idx_change_operation` (`change_operation`),
  KEY `idx_execute_status` (`execute_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='字典项变更明细表';
